### ISSUE TITLE
The 'Contribute to the guide' link broken!

### ISSUE THREAD

**Issue by Codeize** [MenuDocs/guides#6]
When clicking on the contribute link it resolves a 404 error. I noticed this on the discord.js guide, it may occur on every guide.

Thanks.

**Comment by Strandxo** [comment]
I've worked out the issue, I'll hopefully provide a fix by the end of the day. It's to do with the structure of the entire docs vs how vuepress provides the link to the specific files. Once fixed, I'll let you know and close this issue.

**Comment by Codeize** [comment]
Thanks Connor and Anthony, have a good one.
